//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbsys.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class employeemanageEntities : DbContext
    {
        public employeemanageEntities()
            : base("name=employeemanageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<roles> roles { get; set; }
        public DbSet<salary> salary { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<userAccount> userAccount { get; set; }
        public DbSet<userInformation> userInformation { get; set; }
        public DbSet<vw_all_roles> vw_all_roles { get; set; }
    }
}
