//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbsys.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public roles()
        {
            this.userAccount = new HashSet<userAccount>();
        }
    
        public int roleId { get; set; }
        public string roleType { get; set; }
    
        public virtual ICollection<userAccount> userAccount { get; set; }
    }
}
