//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbsys.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class userInformation
    {
        public int userInfoId { get; set; }
        public string userInFname { get; set; }
        public string userInLname { get; set; }
        public string userInEmail { get; set; }
        public string userInAddress { get; set; }
        public int userId { get; set; }
    
        public virtual userAccount userAccount { get; set; }
    }
}
