//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbsys.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAccount
    {
        public userAccount()
        {
            this.salary = new HashSet<salary>();
            this.userInformation = new HashSet<userInformation>();
        }
    
        public int userId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int roleId { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual ICollection<salary> salary { get; set; }
        public virtual ICollection<userInformation> userInformation { get; set; }
    }
}
